# kernels/BUILD.bazel
load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_cuda//cuda:defs.bzl", "cuda_library")

filegroup(
    name = "kernels_header",
    srcs = ["kernels.cu.h"],
    visibility = ["//visibility:public"],
)

[
    cuda_library(
        name = dir.split("/")[0],
        srcs = [dir],
        hdrs = [":kernels_header"],
        deps = ["//src:gpu_utils"],
        copts = ["-Isrc"],
        visibility = ["//bindings:__pkg__"],
    )
    for dir in glob(["*/kernel.cu"])
]

cc_library(
    name = "all_kernels",
    deps = [":" + dir.split("/")[0] for dir in glob(["*/kernel.cu"])],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "kernels_dir",
    srcs = glob(["**/*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "test_data",
    srcs = glob([
        "**/tests/**/*.bin",
        "**/tests/**/*.py",
    ]),
    visibility = ["//visibility:public"],
)